### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by udeaghad** [udeaghad/Recipe-app#12]
In this issue,
- we have created a kanban board assigning tasks as follows:
   - @kwekubright - inventories 🧾 
   - @udeaghad  - food 🥫 
   - @SaidRasinlic - Recipe 🍨 

Click here for the [here](https://github.com/users/udeaghad/projects/6) to the github project

Kindly review and approve.

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @udeaghad, @kwekubright, and @SaidRasinlic,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have not provided the link to the kanban board. Simply edit your issue above accordingly

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by codepantha** [comment]
# STATUS: APPROVED 🟢 ✔️ 

## Hi team 👋, 

Your Kanban board has been set up correctly!  There is nothing else to say other than... it's time to start building 🚀  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
